title: Your Name
description: subtitle | affiliations | motto
baseurl: ''
url: ''
email: null
highlighter: rouge
markdown: kramdown
paginate: 4
permalink: '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
facebook: '#'
twitter: '#'
linkedin: '#'
github: '#'
researchgate: '#'
orcid: '#'
analytics: null
compress_html:
  clippings:
    - html
    - div
    - p
    - ul
    - td
    - h1
    - h2
    - h3
    - h4
    - link
    - meta
    - footer
    - nav
    - img
    - header
    - hr
    - br
    - head
    - style
    - li
    - ul
    - ol
    - time
    - main
    - script
    - title
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - all
  ignore:
    envs:
      - local
  blanklines: false
  profile: false
  startings: []
collections:
  projects:
    output: true
    permalink: '/projects/:path/'
sass:
  sass_dir: /assets/css/_sass
  style: compressed
include:
  - _pages
exclude:
  - README.md
  - LICENSE.md
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
